# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import testProcess_pb2 as testProcess__pb2


class TestProcessStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TestHello = channel.unary_unary(
                '/testProcess.TestProcess/TestHello',
                request_serializer=testProcess__pb2.TESTRequest.SerializeToString,
                response_deserializer=testProcess__pb2.TESTReply.FromString,
                )
        self.TestHelloStreamReply = channel.unary_stream(
                '/testProcess.TestProcess/TestHelloStreamReply',
                request_serializer=testProcess__pb2.TESTRequest.SerializeToString,
                response_deserializer=testProcess__pb2.TESTReply.FromString,
                )


class TestProcessServicer(object):
    """Missing associated documentation comment in .proto file."""

    def TestHello(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TestHelloStreamReply(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TestProcessServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TestHello': grpc.unary_unary_rpc_method_handler(
                    servicer.TestHello,
                    request_deserializer=testProcess__pb2.TESTRequest.FromString,
                    response_serializer=testProcess__pb2.TESTReply.SerializeToString,
            ),
            'TestHelloStreamReply': grpc.unary_stream_rpc_method_handler(
                    servicer.TestHelloStreamReply,
                    request_deserializer=testProcess__pb2.TESTRequest.FromString,
                    response_serializer=testProcess__pb2.TESTReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'testProcess.TestProcess', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TestProcess(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def TestHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/testProcess.TestProcess/TestHello',
            testProcess__pb2.TESTRequest.SerializeToString,
            testProcess__pb2.TESTReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TestHelloStreamReply(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/testProcess.TestProcess/TestHelloStreamReply',
            testProcess__pb2.TESTRequest.SerializeToString,
            testProcess__pb2.TESTReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
