# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: testProcess.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11testProcess.proto\x12\x0btestProcess\"\x1e\n\x0bTESTRequest\x12\x0f\n\x07\x66\x65\x61ture\x18\x01 \x01(\t\"\x19\n\tTESTReply\x12\x0c\n\x04name\x18\x01 \x01(\t2\x9c\x01\n\x0bTestProcess\x12?\n\tTestHello\x12\x18.testProcess.TESTRequest\x1a\x16.testProcess.TESTReply\"\x00\x12L\n\x14TestHelloStreamReply\x12\x18.testProcess.TESTRequest\x1a\x16.testProcess.TESTReply\"\x00\x30\x01\x42\x36\n\x1bio.grpc.examples.helloworldB\x0fHelloWorldProtoP\x01\xa2\x02\x03HLWb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'testProcess_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\033io.grpc.examples.helloworldB\017HelloWorldProtoP\001\242\002\003HLW'
  _globals['_TESTREQUEST']._serialized_start=34
  _globals['_TESTREQUEST']._serialized_end=64
  _globals['_TESTREPLY']._serialized_start=66
  _globals['_TESTREPLY']._serialized_end=91
  _globals['_TESTPROCESS']._serialized_start=94
  _globals['_TESTPROCESS']._serialized_end=250
# @@protoc_insertion_point(module_scope)
